.catalog:
  name: "PowerDNS DNS"
  version: "v0.4.1-powerdns"
  description: Rancher External DNS service powered by PowerDNS.
  minimum_rancher_version: v0.44.0
  uuid: external-dns-powerdns:v0.4.1-powerdns
  questions:
    - variable: POWERDNS_URL
      label: PowerDNS URL
      type: string
      description: http[s] base url to PowerDNS
      required: true
      default: http://powerdns.example.com:8100
    - variable: POWERDNS_API_KEY
      label: PowerDNS API Key
      type: password
      description: API Key for PowerDNS
      required: true
    - variable: "TTL"
      label: "TTL"
      description: "The resource record cache time to live (TTL), in seconds"
      type: "int"
      default: 299
      required: false
    - variable: "ROOT_DOMAIN"
      label: "Hosted zone name"
      description: "Hosted zone name (zone has to be pre-created). DNS entries will be created for <service>.<stack>.<environment>.<hosted zone>"
      type: "string"
      required: true
      default: moo.example.com

powerdns:
  health_check:
    port: 1000
    interval: 30000
    unhealthy_threshold: 3
    request_line: GET / HTTP/1.0
    healthy_threshold: 2
    response_timeout: 2000
