mysql:
  image: mysql:5.7.12
  expose:
    - 3306
  environment:
    MYSQL_ROOT_PASSWORD: ${mysql_root_password}
    MYSQL_DATABASE: ${mysql_database}
    MYSQL_USER: ${mysql_user}
    MYSQL_PASSWORD: ${mysql_password}
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.pull_image: always

powerdns-server:
  image: jgreat/powerdns:latest
  ports:
    - 53:5300/tcp
    - 53:5300/udp
  expose:
    - 8000/tcp
  environment:
    MYSQL_HOST: mysql
    MYSQL_PORT: '3306'
    MYSQL_DATABASE: ${mysql_database}
    MYSQL_USER: ${mysql_user}
    MYSQL_PASSWORD: ${mysql_password}
    WEBSERVER: 'true'
    WEBSERVER_PASSWORD: ${webserver_password}
    PDNS_SOA_NAME: ns1.${domain_name}
    PDNS_SOA_MAIL: ${email}
    MODE_MASTER: 'true'
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.pull_image: always
  links:
    - mysql:mysql

powerdns:
  image: rancher/load-balancer-service
  ports:
    - 8100:8000
  links:
    - powerdns-server:powerdns-server
  labels:
    io.rancher.loadbalancer.ssl.ports: '8100'
    io.rancher.container.hostname_override: container_name
