.catalog:
  name: PowerDNS
  version: 3.4.8-1
  description: PowerDNS server with MYSQL backend
  uuid: powerdns-3.4.8-1
  questions:
    - variable: mysql_database
      label: MySQL Database
      type: string
      required: true
      default: pdns
    - variable: mysql_user
      label: MySQL Database User
      type: string
      required: true
      default: pdns
    - variable: mysql_password
      label: MySQL Database Password
      type: password
      required: true
    - variable: mysql_root_password
      label: MySQL Root Password
      type: password
      required: true
    - variable: domain_name
      label: Base Domain
      description: The base domain i.e. moo.example.com
      type: string
      required: true
    - variable: email
      label: SOA Email Address
      description: Email address listed in the SOA record
      type: string
      required: true
    - variable: webserver_password
      label: API Key
      description: PowerDNS API Access Key
      type: password
      required: true
    - variable: cert_name
      label: SSL Cert Name
      description: SSL Cert Regestered in Rancher
      type: certificate
      required: true

powerdns-server:
  scale: 1
  health_check:
    port: 8000
    interval: 10000
    unhealthy_threshold: 2
    request_line: ''
    strategy: none
    healthy_threshold: 2
    response_timeout: 1000

mysql:
  scale: 1
  health_check:
    port: 3306
    interval: 10000
    unhealthy_threshold: 2
    request_line: ''
    strategy: none
    healthy_threshold: 2
    response_timeout: 1000

powerdns:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  default_cert: "${cert_name}"
  health_check:
    port: 42
    interval: 10000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 10000
